use_frameworks!

platform :ios, '8.0'

target 'LMMCoreFoundation_Example' do
  pod 'LMMCoreFoundation', :path => '../'

  target 'LMMCoreFoundation_Tests' do
    inherit! :search_paths

    
  end
end
